# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160320_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ('-created',)},
        ),
    ]
