# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160320_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={},
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='created',
        ),
    ]
