# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160320_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
