# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_friendship_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
