# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_choice_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='sex',
        ),
    ]
