# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160323_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='f_sex',
            new_name='f_votes',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='m_sex',
            new_name='m_votes',
        ),
    ]
