# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('verify_code', models.CharField(max_length=25)),
            ],
        ),
    ]
