# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160420_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsettings',
            old_name='notify',
            new_name='vote_notify',
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='follow_notify',
            field=models.BooleanField(default=True),
        ),
    ]
