# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20160420_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsettings',
            options={'verbose_name_plural': 'Account settin'},
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
