# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20160530_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='eligible_gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
