# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_question_eligible_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='eligibility',
            field=models.BooleanField(default=False),
        ),
    ]
